# default configuration
baseURL = "https://sassie.me"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Sassie.me"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about/"
name = "About"
weight = 1

[[menu.main]]
URL = "CV.pdf"
name = "CV"
weight = 4

[[menu.main]]
URL = "portfolio/"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact/"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#eda6bf"
# contact info
phone = "+33 6 66 48 53 76"
email = "jobs@sassie.me"
address = "14000, Caen France"
# meta description
author = "Sassie"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Copyright &copy; 2022 Sassie"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/xdobjazp" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "49.182139"
map_longitude = "-0.370690"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/sassie/"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/sassie_bee_me/"

[[params.social]]
icon = "ti-dribbble"
URL = "https://dribbble.com/sassie_bee_me"
